---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Introducing maintainr

Functions to synchronize package installation and libraries across multiple 
computers on multiple platforms. This workflow should also make upgrading R on 
Windows much more straightforward, and allow for the synchronization of packages 
among versions of R on the same machine or across machines.

The basic workflow is simple, but the idea of the package is to create a way to 
allow lots of flexibility to users--such as composing and synchronizing an 
RProfile and Renviron file within R. 

To install `maintainr`: 

```
library(devtools)
install_github("jknowles/maintainr")
library(maintainr)
```

The first step is to get a csv file of installed packages (so it is human readable as well) with the function `save_pkgs()`. 

```
# For example
PATH <- "Path/To/My/Dropbox"
savePkgs(PATH, "mypkglist.csv")
```

After packages have been stored, then the user can restore the installed packages 
either to a new library (to create a sitewide library for example) or on a 
new machine, using the following workflow:

```
PATH <- "Path/to/My/Packagefile"

mypkgs <- readPkgs(PATH, "mypkglist.csv")

newlib <- "Path/to/new/pkg_library"

installPkgs(mypkgs,newlib)

addNewLib(newlib)

```

After we have installed the packages into a new library, we need to tell R how 
to find that library. For now, the options to do this are quite limited. The 
best way is to borrow the code from [Tal Galili](http://stackoverflow.com/questions/1401904/painless-way-to-install-a-new-version-of-r-on-windows) 
to create a new .Renviron file. Currently this function only allows for a 
library that is in the parent of the R home directory, but will be updated soon
to fix this:

```
setLibrary()

```

Once this is done, when R is restarted, the new library will be the default 
library. Cleaning out old libraries will need to be handled by a separate 
function yet to be written. 

### Contributing

Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.
